name: checker

on:
    workflow_run:
        workflows: [get_raw_proxy]
        types:
            - completed
    
jobs:
    Run:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v4
            - name: run app
              run: python check_all.py
