name: get_raw_proxy

on:  
    push:
        branches:
        - main
    workflow_run:
        workflows: [checker]
        types:
            - completed
    
jobs:
    Run:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v4
           # - name: get ready
           #   run: pip install requests
            - name: run app
              run: python proxy_raw.py
